### ISSUE TITLE
Student Show page lists sessions

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/cep-ui#19]
# Summary

As a volunteer, I would like to see all my recent sessions with a particular student from the student show page.

## Things to Consider

Session listing ALSO exists on the home page. But that list includes all sessions from all students. This listing is specific to the student.

Blocked by #18 

# Criteria for Completion
 - [ ] List all the student sessions from most recent to latest that are specific to the student.
 - [ ] Date formatting and duration should be consistent with mockup
 - [ ] Add test(s)

<img width="200" alt="Screen Shot 2021-10-10 at 7 02 23 PM" src="https://user-images.githubusercontent.com/12770108/136715759-102ca3e5-ca7f-466c-8ec0-04dc44eaae3b.png">

**Comment by garettarrowood** [comment]
https://us04web.zoom.us/j/5709307780?pwd=ZWluZjhXQjZmb0xRZitSV1g1TVp5Zz09

**Comment by gillianwenhold** [comment]
I'll take this one!
