### ISSUE TITLE
Show "No Sessions" svg when there are no sessions

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/cep-ui#42]
# Summary

As a volunteer, I'd like to see something nice when I first log into the app and do not yet have any completed surveys(/sessions).

# Things to consider

Ping Garett / InKind lead on Slack for svg file.

# Criteria for Completion
 - [ ] Logging into the app as a volunteer WITHOUT any sessions shows the nice description and image in the mockup.

<img width="211" alt="Screen Shot 2021-10-13 at 2 07 11 PM" src="https://user-images.githubusercontent.com/12770108/137188916-13a11fd1-1225-4c7b-918c-dbf0eda2d2ec.png">

**Comment by kellyeryan** [comment]
I'll take this one.
