### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/cep-ui#49]
# Summary

As a volunteer, I want to be able to logout of the app.

## Things to Consider

The Account page holds the spot where the logout link is.

# Criteria for Completion
 - [ ] When a user clicks "Logout", they are logged out and redirected to the login screen.

<img width="209" alt="Screen Shot 2021-10-14 at 11 57 52 AM" src="https://user-images.githubusercontent.com/12770108/137354496-cabf2747-4e44-43bd-8d9c-c8e318380ff4.png">

**Comment by rodolfoasantos** [comment]
@garettarrowood I can take this one.
